# Generated by Django 5.2.18 on 2026-10-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="announced_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="anunciado por push em",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="lembrete enviado em",
            ),
        ),
    ]
