# Generated by Django 5.2.18 on 2026-10-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_announced_at_registration_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="ID na ETK",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="external_url",
            field=models.URLField(
                blank=True, editable=False, verbose_name="página de bilhetes"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(
                blank=True, editable=False, verbose_name="imagem (URL)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="synced_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="sincronizado em"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_prices",
            field=models.JSONField(
                blank=True, default=list, editable=False, verbose_name="bilhetes"
            ),
        ),
    ]
