# Generated by Django 5.2.18 on 2026-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_external_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="confirmation_deadline",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="prazo de confirmação",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="confirmation_opens_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="confirmação abre"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_mode",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="ETK: direct ou preregistration (pré-inscrição + confirmação).",
                max_length=20,
                verbose_name="modo de inscrição",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="external_ticket_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="bilhete ETK",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_checkout_url",
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_entered",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="entrou (ETK)"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_expires_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_instructions",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_payment",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                verbose_name="pagamento (ETK)",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_price_name",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_qr",
            field=models.CharField(blank=True, editable=False, max_length=60),
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_synced_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="via_app",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="comprado na app"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmada"),
                    ("cancelled", "Cancelada"),
                    ("pending", "A aguardar pagamento"),
                ],
                default="confirmed",
                max_length=12,
                verbose_name="estado",
            ),
        ),
    ]
