# Generated by Django 5.2.18 on 2026-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_etk_tickets"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("synced_at", models.DateTimeField()),
            ],
        ),
    ]
