# Generated by Django 5.2.18 on 2026-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_sync_cursor"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_id", models.CharField(max_length=40, unique=True)),
                ("event", models.CharField(max_length=40)),
                ("ticket_id", models.CharField(blank=True, max_length=40)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="registration",
            name="ticket_updated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="`updatedAt` do último estado aplicado: estados mais antigos são ignorados.",
                null=True,
                verbose_name="bilhete actualizado na ETK",
            ),
        ),
    ]
