# Generated by Django 5.2.18 on 2026-10-07 15:18

from django.db import migrations, models

from apps.accounts.phone import normalize_phone


def backfill(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.exclude(phone=""):
        User.objects.filter(pk=user.pk).update(phone_e164=normalize_phone(user.phone))



class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_e164",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Normalizado para cruzar com os bilhetes da ETK.",
                max_length=12,
                verbose_name="telemóvel (258…)",
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
