# Generated by Django 5.2.18 on 2026-10-07 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        max_length=700, unique=True, verbose_name="endpoint"
                    ),
                ),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dispositivo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último envio com sucesso"
                    ),
                ),
                (
                    "failures",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="falhas seguidas"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="membro",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscrição push",
                "verbose_name_plural": "subscrições push",
                "ordering": ["-created_at"],
            },
        ),
    ]
